version: "3.9"

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: "mongodb://mongo:27017/tmtc" # point to Docker Mongo container
      JWT_SECRET: "projectsecretkey"
      REDIS_URI: "redis://redis:6379"
    depends_on:
      - redis
      - mongo
    networks:
      - tmtc-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - tmtc-network

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: tmtc
    networks:
      - tmtc-network
    volumes:
      - mongo-data:/data/db

networks:
  tmtc-network:
    driver: bridge

volumes:
  mongo-data:
